import { ThemeProvider } from "@/providers/ThemeProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "@/providers/AuthProvider";
import ToasterProvider from "@/providers/ToasterProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Real-time Chat App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${inter.className} bg-[#ffffff] dark:bg-[#09090b]`}
            >
                <ThemeProvider attribute="class">
                    <AuthProvider>{children}</AuthProvider>
                    <ToasterProvider />
                </ThemeProvider>
            </body>
        </html>
    );
}
